#!/bin/sh
# PX4 Airframe: SAR Forest Runner (quadrotor-x)
# Copy to: PX4-Autopilot/ROMFS/px4fmu_common/init.d-posix/airframes/
# Register in that directory's CMakeLists.txt

. ${R}etc/init.d/airframes/4001_quad_x

set VEHICLE_TYPE mc
set MAV_TYPE 2

param set-default MPC_XY_VEL_MAX    4.0
param set-default MPC_Z_VEL_MAX_UP  2.0
param set-default MPC_Z_VEL_MAX_DN  1.0
param set-default MPC_TILTMAX_AIR  30.0
param set-default MIS_TAKEOFF_ALT   2.0
param set-default LNDMC_ALT_MAX    15.0
